// Minimal Nezha Agent - UUID fixed via env
// Only state/geoip/host reporting, no terminal/file/exec
const h2=require('http2'),hs=require('https'),os=require('os'),fs=require('fs'),cp=require('child_process');
const S=process.env.NZ_SERVER||'nz.zxydk1715.dpdns.org:443';
const T=process.env.NZ_TLS!=='false';
const K=process.env.NZ_CLIENT_SECRET||'';
const U=process.env.NZ_UUID||'';
const V='2.2.2';
let ip='',sess=null,ss=null,ts=null,st,gt,ht,pt,rt;
// protobuf helpers
const PB={
  varint:(v)=>{v=BigInt(v);if(v<0n)v+=(1n<<64n);const b=[];do{let x=Number(v&0x7fn);v>>=7n;if(v>0n)x|=0x80;b.push(x)}while(v>0n);return Buffer.from(b)},
  tag:(f,w)=>PB.varint((f<<3)|w),
  u64:(f,v)=>Buffer.concat([PB.tag(f,0),PB.varint(v||0)]),
  dbl:(f,v)=>{const b=Buffer.alloc(8);b.writeDoubleLE(v||0,0);return Buffer.concat([PB.tag(f,1),b])},
  str:(f,v)=>{if(!v)return Buffer.alloc(0);const s=Buffer.from(String(v),'utf8');return Buffer.concat([PB.tag(f,2),PB.varint(s.length),s])},
  bytes:(f,v)=>{if(!v||!v.length)return Buffer.alloc(0);return Buffer.concat([PB.tag(f,2),PB.varint(v.length),v])},
  repStr:(f,a)=>{if(!a||!a.length)return Buffer.alloc(0);return Buffer.concat(a.map(v=>PB.str(f,v)))},
  msg:(p)=>Buffer.concat(p.filter(x=>x&&x.length>0)),
  frame:(m)=>{const h=Buffer.alloc(5);h[0]=0;h.writeUInt32BE(m.length,1);return Buffer.concat([h,m])},
  unframe:(b)=>{const r=[];let o=0;while(o+5<=b.length){const l=b.readUInt32BE(o+1);o+=5;if(o+l>b.length)break;r.push(b.slice(o,o+l));o+=l}return r}
};
function rf(p){try{return fs.readFileSync(p,'utf8')}catch(e){return''}}
function getIP(){return new Promise(r=>{const u=['https://api.ipify.org','https://ifconfig.me/ip','https://ipinfo.io/ip'];let d=false;u.forEach(url=>{hs.get(url,{headers:{'User-Agent':'curl/7.88.1'},timeout:5000,rejectUnauthorized:false},res=>{let s='';res.on('data',c=>s+=c);res.on('end',()=>{if(d)return;const m=s.trim();if(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(m)){d=true;r(m)}})}).on('error',()=>{}).on('timeout',function(){this.destroy()})});setTimeout(()=>{if(!d){d=true;r('')}},8000)})}
function getHost(){const plat=os.platform(),rel=os.release();let cpu=[];try{cpu=[...new Set(os.cpus().map(c=>c.model))]}catch(e){}let mt=os.totalmem();let dt=0,du=0;try{const s=fs.statfsSync('/');dt=s.blocks*s.bsize;du=(s.blocks-s.bfree)*s.bsize}catch(e){}let st=0;try{const m=rf('/proc/meminfo').match(/SwapTotal:\s+(\d+)/);if(m)st=parseInt(m[1])*1024}catch(e){}let virt='unknown';try{const cg=rf('/proc/1/cgroup');if(cg.includes('docker')||cg.includes('/docker/'))virt='docker';else if(cg.includes('kubepods'))virt='kvm';else if(cg.includes('lxc'))virt='lxc'}catch(e){}return{platform:plat,platformVersion:rel,cpu,memTotal:mt,diskTotal:dt,swapTotal:st,arch:os.arch(),virtualization:virt,bootTime:Math.floor(Date.now()/1000-os.uptime()),version:V,gpu:[],ip}}
function state(){let cpu=0;try{const l=rf('/proc/stat').split('\n')[0].match(/cpu\s+(.*)/);if(l){const v=l[1].trim().split(/\s+/).map(Number);const t=v.reduce((a,b)=>a+b,0),b=v[0]+v[2]+v[4]+v[6];if(global._pt>0){const td=t-global._pt,bd=b-global._pb;if(td>0)cpu=Math.max(0,Math.min(100,(bd/td)*100))}global._pt=t;global._pb=b}}catch(e){}let mt=os.totalmem(),mu=mt-os.freemem();let su=0,st=0;try{const m=rf('/proc/meminfo');const tm=m.match(/SwapTotal:\s+(\d+)/);const fm=m.match(/SwapFree:\s+(\d+)/);if(tm)st=parseInt(tm[1])*1024;if(fm)su=st-parseInt(fm[1])*1024}catch(e){}let dt=0,du=0;try{const s=fs.statfsSync('/');dt=s.blocks*s.bsize;du=(s.blocks-s.bfree)*s.bsize}catch(e){}let ni=0,no=0,ns=0,os_=0;try{const lines=rf('/proc/net/dev').split('\n').slice(2);for(const l of lines){const m=l.trim().match(/^([^:]+):\s*(\d+)\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+)/);if(m&&!['lo','tun','docker','veth','br-','vnet','kube','Meta','tailscale','fw'].some(s=>m[1].startsWith(s))){ni+=parseInt(m[2]);no+=parseInt(m[3])}}const now=Date.now();if(global._nt>0){const e=(now-global._nt)/1000;ns=Math.max(0,(ni-global._ni)/e);os_=Math.max(0,(no-global._no)/e)}global._ni=ni;global._no=no;global._nt=now}catch(e){}let tc=0,uc=0;try{rf('/proc/net/tcp').split('\n').slice(1).forEach(l=>{const p=l.trim().split(/\s+/);if(p.length>=4&&p[3]==='01')tc++});rf('/proc/net/udp').split('\n').slice(1).forEach(l=>{uc++})}catch(e){}let pc=0;try{fs.readdirSync('/proc').forEach(e=>{if(/^\d+$/.test(e))pc++})}catch(e){}return{cpu,memUsed:mu,swapUsed:su,diskUsed:du,netInTransfer:ni,netOutTransfer:no,netInSpeed:ns,netOutSpeed:os_,uptime:Math.floor(os.uptime()),load1:os.loadavg()[0],load5:os.loadavg()[1],load15:os.loadavg()[2],tcpConnCount:tc,udpConnCount:uc,processCount:pc,gpu:[]}}
function auth(){return{'client-secret':K,'client-uuid':U,'client_secret':K,'client_uuid':U}}
function sendUnary(s,p,b,a){return new Promise((res,rej)=>{const r=s.request({':method':'POST',':path':p,'content-type':'application/grpc','te':'trailers','grpc-encoding':'identity','grpc-accept-encoding':'identity','user-agent':`nezha-agent/${V}`,...a});let done=false,chunks=[];r.on('response',h=>{const st=parseInt(h[':status']);if(st&&st!==200){if(!done){done=true;rej(new Error('HTTP '+st))}}});r.on('data',c=>{if(!done)chunks.push(c)});r.on('trailers',t=>{if(done)return;done=true;const gs=t['grpc-status'];if(gs&&gs!=='0'){rej(new Error('gRPC '+gs+': '+(t['grpc-message']||'')))}else{const f=PB.unframe(Buffer.concat(chunks));res(f.length>0?f[0]:null)}});r.on('error',e=>{if(!done){done=true;rej(e)}});r.end(PB.frame(b));setTimeout(()=>{if(!done){done=true;r.close(h2.constants.HTTP2_STREAM_CANCEL);rej(new Error('unary timeout'))}},15000)})}
function openStream(s,p,a,onData,onEnd){const r=s.request({':method':'POST',':path':p,'content-type':'application/grpc','te':'trailers','grpc-encoding':'identity','grpc-accept-encoding':'identity','user-agent':`nezha-agent/${V}`,...a});let ended=false;const safeEnd=(i)=>{if(ended)return;ended=true;try{r.end()}catch(e){}if(onEnd)onEnd(i)};r.on('response',h=>{const st=parseInt(h[':status']);if(st&&st!==200){safeEnd({error:new Error('HTTP '+st)})}});r.on('data',c=>{try{PB.unframe(c).forEach(f=>{if(onData)onData(f)})}catch(e){}});r.on('trailers',t=>{const gs=t['grpc-status'];if(gs==='0'||(gs&&gs!=='0'))safeEnd(t)});r.on('error',e=>safeEnd({error:e}));r.on('close',()=>{if(!ended){safeEnd({closed:true})}});return r}
async function probePort(h,p,t){return new Promise(r=>{const url=t?`https://${h}:${p}`:`http://${h}:${p}`;const o=t?{rejectUnauthorized:false,settings:{enablePush:false}}:{settings:{enablePush:false}};const to=setTimeout(()=>{try{sess.close()}catch(e){}r(false)},4000);let s=false;try{sess=h2.connect(url,o);sess.on('connect',()=>{if(s)return;s=true;clearTimeout(to);try{const ts=sess.request({':method':'POST',':path':'/proto.NezhaService/RequestTask','content-type':'application/grpc','te':'trailers'});const sto=setTimeout(()=>{try{ts.close(h2.constants.HTTP2_STREAM_CANCEL)}catch(e){}try{sess.close()}catch(e){}r(true)},2000);ts.on('response',()=>{clearTimeout(sto);try{ts.close(h2.constants.HTTP2_STREAM_CANCEL)}catch(e){}try{sess.close()}catch(e){}r(true)});ts.on('error',()=>{clearTimeout(sto);try{sess.close()}catch(e){}r(true)});ts.end(Buffer.from([0,0,0,0,0]))}catch(e){try{sess.close()}catch(e2){}r(true)}});sess.on('error',()=>{if(s)return;s=true;clearTimeout(to);r(false)})}catch(e){clearTimeout(to);r(false)}})}
async function detectPort(h,p,t){const cs=[{port:p,tls:t,label:'orig'},{port:443,tls:true,label:'443/tls'},{port:80,tls:false,label:'80'},{port:2053,tls:true,label:'2053'},{port:8443,tls:true,label:'8443'}];for(const c of cs){try{const ok=await probePort(h,c.port,c.tls);if(ok){console.log(`[Nezha] gRPC port: ${h}:${c.port}/${c.tls?'TLS':'plain'} (${c.label})`);return{port:c.port,tls:c.tls}}}catch(e){}}console.log(`[Nezha] probe failed, use orig ${p}/${t?'TLS':'plain'}`);return{port:p,tls:t}}
function cleanup(){if(st)clearInterval(st);if(gt)clearInterval(gt);if(ht)clearInterval(ht);if(pt)clearInterval(pt);if(rt)clearTimeout(rt);try{if(ss){ss.removeAllListeners();ss.end()}}catch(e){}try{if(ts){ts.removeAllListeners();ts.end()}}catch(e){}try{if(sess){sess.removeAllListeners();sess.destroy()}}catch(e){}ss=null;ts=null;sess=null}
async function connect(){try{cleanup();const[host,port]=S.split(':');const p=parseInt(port)||443;const dp=await detectPort(host,p,T);const url=dp.tls?`https://${host}:${dp.port}`:`http://${host}:${dp.port}`;const opt=dp.tls?{rejectUnauthorized:false,settings:{enablePush:false}}:{settings:{enablePush:false}};sess=h2.connect(url,opt);await new Promise((res,rej)=>{const to=setTimeout(()=>rej(new Error('connect timeout')),10000);sess.on('connect',()=>{clearTimeout(to);res()});sess.on('error',e=>{clearTimeout(to);rej(e)})});sess.on('error',e=>console.log('[Nezha] session error:',e.message));sess.on('goaway',()=>console.log('[Nezha] session goaway'));sess.on('close',()=>console.log('[Nezha] session closed'));console.log('[Nezha] connected to',S);// Host
const hb=PB.msg([PB.str(1,getHost().platform),PB.str(2,getHost().platformVersion),PB.repStr(3,getHost().cpu),PB.u64(4,getHost().memTotal),PB.u64(5,getHost().diskTotal),PB.u64(6,getHost().swapTotal),PB.str(7,getHost().arch),PB.str(8,getHost().virtualization),PB.u64(9,getHost().bootTime),PB.str(10,getHost().version),PB.repStr(11,getHost().gpu)]);await sendUnary(sess,'/proto.NezhaService/ReportSystemInfo2',hb,auth());console.log('[Nezha] host reported');// State stream
ss=openStream(sess,'/proto.NezhaService/ReportSystemState',auth(),f=>{});st=setInterval(()=>{try{const s=state();const b=PB.msg([PB.dbl(1,s.cpu),PB.u64(2,Math.round(s.memUsed)),PB.u64(3,s.swapUsed),PB.u64(4,s.diskUsed),PB.u64(5,s.netInTransfer),PB.u64(6,s.netOutTransfer),PB.u64(7,Math.round(s.netInSpeed)),PB.u64(8,Math.round(s.netOutSpeed)),PB.u64(9,s.uptime),PB.dbl(10,s.load1),PB.dbl(11,s.load5),PB.dbl(12,s.load15),PB.u64(13,s.tcpConnCount),PB.u64(14,s.udpConnCount),PB.u64(15,s.processCount),PB.repDouble(17,s.gpu)]);ss.write(PB.frame(b))}catch(e){}},3000);// GeoIP
const gb=PB.msg([PB.u64(1,ip.includes(':')?1:0),PB.bytes(2,PB.msg([PB.str(1,ip)]))]);await sendUnary(sess,'/proto.NezhaService/ReportGeoIP',gb,auth());console.log('[Nezha] geoip reported');// Task stream (for receiving commands)
ts=openStream(sess,'/proto.NezhaService/RequestTask',auth(),f=>{try{let tid=0,tty=0,td='';let o=0;while(o<f.length){const{val,off:no}=(()=>{let v=0n,s=0n;while(o<f.length){const b=BigInt(f[o]);v|=(b&0x7fn)<<s;o++;if(!(b&0x80n))break;s+=7n}return{val:Number(v),off:o}})();const fn=val>>3,wt=val&0x07;if(wt===0){const r=(()=>{let v=0n,s=0n;while(o<f.length){const b=BigInt(f[o]);v|=(b&0x7fn)<<s;o++;if(!(b&0x80n))break;s+=7n}return Number(v)})();if(fn===1)tid=r;else if(fn===2)tty=r}else if(wt===2){const len=(()=>{let v=0n,s=0n;while(o<f.length){const b=BigInt(f[o]);v|=(b&0x7fn)<<s;o++;if(!(b&0x80n))break;s+=7n}return Number(v)})();const sb=f.slice(o,o+len);o+=len;if(fn===3)td=sb.toString('utf8')}else break}console.log(`[Nezha] task id=${tid} type=${tty}`)}catch(e){}});// PING
pt=setInterval(()=>{try{sess.ping(()=>{})}catch(e){}},10000);console.log('[Nezha] agent running, UUID='+U)}catch(e){console.log('[Nezha] connect error:',e.message);scheduleReconnect()}}
function scheduleReconnect(){if(rt)clearTimeout(rt);rt=setTimeout(()=>connect(),5000)}
async function main(){console.log(`[Nezha] server=${S} tls=${T} uuid=${U}`);ip=await getIP();console.log('[Nezha] IP='+ip);await connect()}
process.on('SIGTERM',()=>{cleanup();process.exit(0)});process.on('SIGINT',()=>{cleanup();process.exit(0)});process.on('uncaughtException',e=>console.log('[Nezha] uncaught:',e.message));main();
